// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxWKNzBTJ_d_b3QlrteOQbL9Uwq4SL91Q',
    appId: '1:745201346285:web:7cae7104d5a1b738aa0ee4',
    messagingSenderId: '745201346285',
    projectId: 'chatapp-54b79',
    authDomain: 'chatapp-54b79.firebaseapp.com',
    storageBucket: 'chatapp-54b79.appspot.com',
    measurementId: 'G-ZX7GFH2BNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtEO3SOunD_ZT8_FgHZoufT55DwrQsyKc',
    appId: '1:745201346285:android:44ff22d3e127c7ffaa0ee4',
    messagingSenderId: '745201346285',
    projectId: 'chatapp-54b79',
    storageBucket: 'chatapp-54b79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCLBb1cnxMohdDfsjAHvTGrcedu_EfD2Q',
    appId: '1:745201346285:ios:bb86980e0aa183b3aa0ee4',
    messagingSenderId: '745201346285',
    projectId: 'chatapp-54b79',
    storageBucket: 'chatapp-54b79.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCLBb1cnxMohdDfsjAHvTGrcedu_EfD2Q',
    appId: '1:745201346285:ios:bb86980e0aa183b3aa0ee4',
    messagingSenderId: '745201346285',
    projectId: 'chatapp-54b79',
    storageBucket: 'chatapp-54b79.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxWKNzBTJ_d_b3QlrteOQbL9Uwq4SL91Q',
    appId: '1:745201346285:web:fa2da054bd1999c5aa0ee4',
    messagingSenderId: '745201346285',
    projectId: 'chatapp-54b79',
    authDomain: 'chatapp-54b79.firebaseapp.com',
    storageBucket: 'chatapp-54b79.appspot.com',
    measurementId: 'G-T9VWNVTVYJ',
  );
}
